// <auto-generated />
using System;
using GroceryStore.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroceryStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317111254_AddIdentitySupport")]
    partial class AddIdentitySupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroceryStore.Database.Entities.Attribute.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("p_k_attributes");

                    b.ToTable("attributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = 3,
                            MaxValue = 100m,
                            MinValue = 0m,
                            Name = "Fat Content",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 2,
                            DataType = 2,
                            MaxValue = 10000m,
                            MinValue = 0m,
                            Name = "Weight",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 3,
                            DataType = 2,
                            MaxValue = 10000m,
                            MinValue = 0m,
                            Name = "Volume",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 4,
                            DataType = 1,
                            Name = "Milk Source"
                        },
                        new
                        {
                            Id = 5,
                            DataType = 1,
                            Name = "Base Ingredient"
                        },
                        new
                        {
                            Id = 6,
                            DataType = 1,
                            Name = "Flavor"
                        },
                        new
                        {
                            Id = 7,
                            DataType = 1,
                            Name = "Mold Type"
                        },
                        new
                        {
                            Id = 8,
                            DataType = 5,
                            MaxValue = 1m,
                            MinValue = 0m,
                            Name = "Lactose Free"
                        },
                        new
                        {
                            Id = 9,
                            DataType = 3,
                            MaxValue = 100m,
                            MinValue = 0m,
                            Name = "Sugar Content",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 10,
                            DataType = 5,
                            MaxValue = 1m,
                            MinValue = 0m,
                            Name = "Contains Filling"
                        },
                        new
                        {
                            Id = 11,
                            DataType = 3,
                            MaxValue = 100m,
                            MinValue = 0m,
                            Name = "Alcohol Content",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 13,
                            DataType = 5,
                            MaxValue = 1m,
                            MinValue = 0m,
                            Name = "Organic"
                        },
                        new
                        {
                            Id = 16,
                            DataType = 3,
                            Name = "Temperature Storage"
                        });
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Brand.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_brands");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_brands_name");

                    b.ToTable("brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Generic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coca-Cola"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pepsi"
                        });
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Category.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("p_k_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("i_x_categories_parent_id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dairy Products"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Meat & Poultry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fish & Seafood"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bakery & Pastry"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Vegetables & Fruit"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Alcohol"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Household Chemicals"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Personal Care & Hygiene"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Milk",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Drinkable Fermented",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Spoonable Dairy & Sour Cream",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Cheese & Cottage Cheese",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Butter",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Animal Milk",
                            ParentId = 12
                        },
                        new
                        {
                            Id = 18,
                            Name = "Plant-Based Milk",
                            ParentId = 12
                        },
                        new
                        {
                            Id = 19,
                            Name = "Traditional Kefir",
                            ParentId = 13
                        },
                        new
                        {
                            Id = 20,
                            Name = "Drinkable Yogurt",
                            ParentId = 13
                        },
                        new
                        {
                            Id = 21,
                            Name = "Hard Cheese",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 22,
                            Name = "Soft & Brine Cheese",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 23,
                            Name = "Mold Cheese",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 24,
                            Name = "Low Alcohol",
                            ParentId = 9
                        },
                        new
                        {
                            Id = 25,
                            Name = "Strong Alcohol",
                            ParentId = 9
                        },
                        new
                        {
                            Id = 26,
                            Name = "Beer",
                            ParentId = 24
                        },
                        new
                        {
                            Id = 27,
                            Name = "Cider",
                            ParentId = 24
                        },
                        new
                        {
                            Id = 28,
                            Name = "Vodka",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 29,
                            Name = "Whiskey",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cognac",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 31,
                            Name = "Rum",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 32,
                            Name = "Tequila",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 33,
                            Name = "Gin",
                            ParentId = 25
                        });
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.CategoryAttribute.CategoryAttribute", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.HasKey("CategoryId", "AttributeId")
                        .HasName("p_k_category_attributes");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("i_x_category_attributes_attribute_id");

                    b.ToTable("category_attributes");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            AttributeId = 1,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 1,
                            AttributeId = 8,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 12,
                            AttributeId = 2,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 12,
                            AttributeId = 4,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 18,
                            AttributeId = 5,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 13,
                            AttributeId = 2,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 20,
                            AttributeId = 6,
                            IsRequired = false
                        },
                        new
                        {
                            CategoryId = 20,
                            AttributeId = 9,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 14,
                            AttributeId = 3,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 14,
                            AttributeId = 6,
                            IsRequired = false
                        },
                        new
                        {
                            CategoryId = 14,
                            AttributeId = 9,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 14,
                            AttributeId = 10,
                            IsRequired = false
                        },
                        new
                        {
                            CategoryId = 16,
                            AttributeId = 3,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 15,
                            AttributeId = 3,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 15,
                            AttributeId = 4,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 23,
                            AttributeId = 7,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 9,
                            AttributeId = 11,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 9,
                            AttributeId = 3,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 26,
                            AttributeId = 6,
                            IsRequired = false
                        },
                        new
                        {
                            CategoryId = 28,
                            AttributeId = 11,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 6,
                            AttributeId = 2,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 3,
                            AttributeId = 2,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 3,
                            AttributeId = 16,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 4,
                            AttributeId = 2,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 4,
                            AttributeId = 16,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 7,
                            AttributeId = 13,
                            IsRequired = false
                        },
                        new
                        {
                            CategoryId = 28,
                            AttributeId = 3,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 29,
                            AttributeId = 11,
                            IsRequired = true
                        },
                        new
                        {
                            CategoryId = 30,
                            AttributeId = 11,
                            IsRequired = true
                        });
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Country.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_countries");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_countries_code");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DE",
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pcs")
                        .HasColumnName("base_unit");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_products");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("i_x_products_brand_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_products_category_id");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("i_x_products_country_id");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasDatabaseName("i_x_products_sku");

                    b.ToTable("products");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.ProductBatch.ProductBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("batch_number");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_closed");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("purchase_price");

                    b.Property<int>("QuantityArrived")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_arrived");

                    b.Property<int>("QuantityRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_remaining");

                    b.Property<DateOnly>("SupplyDate")
                        .HasColumnType("date")
                        .HasColumnName("supply_date");

                    b.HasKey("Id")
                        .HasName("p_k_product_batches");

                    b.HasIndex("ProductId", "ExpirationDate", "SupplyDate")
                        .HasDatabaseName("i_x_product_batches_product_id_expiration_date_supply_date");

                    b.ToTable("product_batches");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.User.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("p_k_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("p_k_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("p_k_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Category.Category", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Category.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.CategoryAttribute.CategoryAttribute", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Attribute.ProductAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_category_attributes_attributes_attribute_id");

                    b.HasOne("GroceryStore.Database.Entities.Category.Category", "Category")
                        .WithMany("Attributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_category_attributes_categories_category_id");

                    b.Navigation("Attribute");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Product.Product", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Brand.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_products_brands_brand_id");

                    b.HasOne("GroceryStore.Database.Entities.Category.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_products_categories_category_id");

                    b.HasOne("GroceryStore.Database.Entities.Country.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_products_countries_country_id");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.ProductBatch.ProductBatch", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_product_batches_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("GroceryStore.Database.Entities.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Brand.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Category.Category", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Children");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
